name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t my-bot .

    # Run Docker container
    - name: Run Docker container
      run: |
        docker run -d -p 8004:8004 my-bot