# Utiliser une image de base Python
FROM python:3.11-slim
# Mettre à jour pip
RUN pip install --upgrade pip
# Installer les dépendances système nécessaires
RUN apt-get update && apt-get install -y \ build-essential \
wget
libpq-dev \
libtool \ autoconf \
&& rm -rf /var/lib/apt/lists/*
# Télécharger et installer TA-Lib à partir des so
RUN
wget http://prdownloads.sourceforge.net/ta-1
tar -xzvf ta-lib-0.4.0-src.tar.gz && \ cd ta-lib && \
•/configure --prefix=/usr && \ make && \ make install && \
cd
.. && \
rm -rf ta-11b-0.4.0-src.tar.gz ta-lib
# Définir le répertoire de travail